### ISSUE TITLE
v 0.3.0 for 1.2 on atmosphere

### ISSUE THREAD

**Issue by tcastelli** [mizzao/meteor-build-fetcher#3]
Hello, I've seen updates on the package for meteor 1.2, but I couldn't see it updated on atmosphere yet, any things that must be tested?

**Comment by mizzao** [comment]
I'm currently getting this error when trying to publish and need to look into it:

```
=> Errors while initializing project:         
                                              
While selecting package versions:
error: unknown package: isobuild:compiler-plugin
Required by: mizzao:build-fetcher 0.3.0
Required by: ecmascript 0.1.3-plugins.1
```

**Comment by mizzao** [comment]
Oh never mind, it's meteor/meteor#5244 that I have to take care of.

**Comment by mizzao** [comment]
v0.3.0 is released on atmosphere now, let me know if you have any issues.

**Comment by tcastelli** [comment]
Thanks the package is up and working, however I've noticed that on every change of the code, the package downloads all files.(Not only when the .json is changed :S)

**Comment by mizzao** [comment]
Does 0.2.0 not do that?

One way to ensure that it doesn't do that is to make a package within your app and have the files downloaded within the package; that way if nothing changes in the package, it'll only download once.

**Comment by tcastelli** [comment]
Nope, with 0.2.0 it doesn't happen.
I have it configured like you said, with one package that is downloading all the files needed from repos, but with 0.3.0 it still downloads everytime I change code from the app(even if the package is unafected).

**Comment by mizzao** [comment]
@tcastelli v0.3.1 should be a lot more efficient now, even when you use `.fetch.json` files outside of a package and in the app itself. Let me know if you have a chance to test it out.

**Comment by tcastelli** [comment]
Everything seems to be working now plus the caching to avoid repeating downloads! :+1:

**Comment by mizzao** [comment]
Great, thanks!

**Comment by tcastelli** [comment]
oops! Just found something when trying to debug my app, (when i tried meteor run everything was working, but with debug i get a weird error)
````js
Errors prevented startup:

While processing files with mizzao:build-fetcher (for target web.browser):
C:\Users\xxxx\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\isobuild\compiler-plugin.js:387:15: 'data' option to addAsset must be a Buffer or String.
  at [object Object]._.extend.addAsset (C:\Users\xxxx\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\isobuild\compiler-plugin.js:387:15)
  at [object Object]._.extend.addAsset (C:\Users\xxxx\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\isobuild\compiler-plugin.js:277:24)
  at Fetcher.addCompileResult (<runJavaScript-51>:135:27)
  at <runJavaScript-50>:352:16
  at C:\Users\xxxx\AppData\Local\.meteor\packages\mizzao_build-fetcher\0.3.1\plugin.fetcher.os\npm\caching-compiler\node_modules\async\lib\async.js:182:20
  at replenish (C:\Users\xxxx\AppData\Local\.meteor\packages\mizzao_build-fetcher\0.3.1\plugin.fetcher.os\npm\caching-compiler\node_modules\async\lib\async.js:317:21)
  at C:\Users\xxxxx\AppData\Local\.meteor\packages\mizzao_build-fetcher\0.3.1\plugin.fetcher.os\npm\caching-compiler\node_modules\async\lib\async.js:328:15
  at Object.async.forEachLimit.async.eachLimit (C:\Users\xxxx\AppData\Local\.meteor\packages\mizzao_build-fetcher\0.3.1\plugin.fetcher.os\npm\caching-compiler\node_modules\async\lib\async.js:221:35)
  at Fetcher.processFilesForTarget (<runJavaScript-50>:324:11)

````

**Comment by mizzao** [comment]
Can you open a new issue for this?

Also, can you describe if this happened the first time you ran the app, or later on after a restart? Also, if you are able to reproduce it consistently, maybe you can try forking a local version of the package and printing out what is causing the issue. It might be possible that the `Buffer` where the PNG was downloaded is no longer valid, or something like that.
